name: Container Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#on:
 # workflow_run:
  #  workflows: [ "Build Vulnerable Docker Image" ]
   # types:
    #  - completed
jobs:
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan container image with Tenable Cloud Security
        uses: tenable/cloud-security-actions/container-image/scan@v1
        with:
          api-token: ${{ secrets.TENABLE_API_TOKEN }}
          api-url: https://uk.app.ermetic.com
          name: vuln-docker
